# Generated by Django 5.0.4 on 2024-05-05 14:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookTitle',
            fields=[
                ('isbn', models.CharField(max_length=13, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PromotionRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BookCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('library_branch_id', models.IntegerField()),
                ('year', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('date_of_return', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booktitle')),
            ],
            options={
                'ordering': ['library_branch_id', '-year'],
            },
        ),
        migrations.CreateModel(
            name='PromotionRowsLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booktitle')),
                ('promotion_row_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.promotionrow')),
            ],
        ),
        migrations.CreateModel(
            name='FavouritesLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.booktitle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['book_title'],
                'unique_together': {('user', 'book_title')},
            },
        ),
    ]
