# Generated by Django 5.0.4 on 2024-05-13 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopy',
            name='is_reservasion_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bookcopy',
            name='is_reserved',
            field=models.BooleanField(default=False),
        ),
    ]
